# I don't like these extra long lines, but don't know a clean
# way to insert line breaks within a string.

# Run tests in throwaway environment based on our clean build environment.
FROM golang_base_image:latest AS tester

# installs curl and wget so we can scrape the GoDoc output.
RUN sh -xc 'apt-get update && apt-get install -y curl wget' 2>&1

# installs the ginkgo CLI and matcher library, and a few others only
# used for testing.
#
#     * github.com/onsi/ginkgo/ginkgo    -- BDD framework that SmartEdge uses
#     * github.com/onsi/gomega/...       -- Matcher library for ginkgo
#     * github.com/xeipuuv/gojsonschema  -- To validate the spec: "conforms to schema..."
#     * github.com/mgechev/revive        -- A configurable version of "golint"
#     * github.com/rakyll/gotest         -- A colorized version of "go test"
#
# None of these is installed when building the production code.
RUN sh -xc                              \
	'for modules in                     \
		github.com/onsi/ginkgo/ginkgo   \
		github.com/onsi/gomega/...      \
		github.com/xeipuuv/gojsonschema \
		github.com/mgechev/revive       \
		github.com/rakyll/gotest        \
	; do                                \
		go get -v -u $modules ;         \
	done' 2>&1

# We manually bind mount the source directory ourselves on use externally.

# Configure the container entrypoint so that it automatically runs all
# the tests, quality metrics and docs generation:
ENTRYPOINT sh -xc \
	"go vet                                                             && \
	\"$GOPATH/bin/revive\" -formatter stylish -config revive.toml ./... && \
	gotest -coverprofile=coverage.out ./...                             && \
	go tool cover -html=coverage.out -o coverage.html                   && \
	./utils/gendoc.sh \"github.com/smartedge/codechallenge\"            && \
	cp utils/redirect.html godoc/index.html                             ;  \
	exit_status=\$?                                                     ;  \
	[ -z \"$EXT_UID_GID\" ] ||                                             \
		chown -R \"$EXT_UID_GID\" godoc coverage.out coverage.html      ;  \
	exit \$exit_status"
